// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Empty           Status = 0
	Status_OK              Status = 200
	Status_ParamInvalid    Status = 300
	Status_EmailInvalid    Status = 301
	Status_EmailRegistered Status = 302
	Status_EmailSendFailed Status = 303
	Status_UserNotExist    Status = 401
	Status_PasswordWrong   Status = 402
)

var Status_name = map[int32]string{
	0:   "Empty",
	200: "OK",
	300: "ParamInvalid",
	301: "EmailInvalid",
	302: "EmailRegistered",
	303: "EmailSendFailed",
	401: "UserNotExist",
	402: "PasswordWrong",
}

var Status_value = map[string]int32{
	"Empty":           0,
	"OK":              200,
	"ParamInvalid":    300,
	"EmailInvalid":    301,
	"EmailRegistered": 302,
	"EmailSendFailed": 303,
	"UserNotExist":    401,
	"PasswordWrong":   402,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type VerifyUserRsp_Result int32

const (
	VerifyUserRsp_OK        VerifyUserRsp_Result = 0
	VerifyUserRsp_NOT_EXIST VerifyUserRsp_Result = 1
	VerifyUserRsp_PWD_WRONG VerifyUserRsp_Result = 2
)

var VerifyUserRsp_Result_name = map[int32]string{
	0: "OK",
	1: "NOT_EXIST",
	2: "PWD_WRONG",
}

var VerifyUserRsp_Result_value = map[string]int32{
	"OK":        0,
	"NOT_EXIST": 1,
	"PWD_WRONG": 2,
}

func (x VerifyUserRsp_Result) String() string {
	return proto.EnumName(VerifyUserRsp_Result_name, int32(x))
}

func (VerifyUserRsp_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6, 0}
}

type IsEmailRegisteredReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRegisteredReq) Reset()         { *m = IsEmailRegisteredReq{} }
func (m *IsEmailRegisteredReq) String() string { return proto.CompactTextString(m) }
func (*IsEmailRegisteredReq) ProtoMessage()    {}
func (*IsEmailRegisteredReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *IsEmailRegisteredReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRegisteredReq.Unmarshal(m, b)
}
func (m *IsEmailRegisteredReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRegisteredReq.Marshal(b, m, deterministic)
}
func (m *IsEmailRegisteredReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRegisteredReq.Merge(m, src)
}
func (m *IsEmailRegisteredReq) XXX_Size() int {
	return xxx_messageInfo_IsEmailRegisteredReq.Size(m)
}
func (m *IsEmailRegisteredReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRegisteredReq.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRegisteredReq proto.InternalMessageInfo

func (m *IsEmailRegisteredReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IsEmailRegisteredRsp struct {
	Registered           bool     `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRegisteredRsp) Reset()         { *m = IsEmailRegisteredRsp{} }
func (m *IsEmailRegisteredRsp) String() string { return proto.CompactTextString(m) }
func (*IsEmailRegisteredRsp) ProtoMessage()    {}
func (*IsEmailRegisteredRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *IsEmailRegisteredRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRegisteredRsp.Unmarshal(m, b)
}
func (m *IsEmailRegisteredRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRegisteredRsp.Marshal(b, m, deterministic)
}
func (m *IsEmailRegisteredRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRegisteredRsp.Merge(m, src)
}
func (m *IsEmailRegisteredRsp) XXX_Size() int {
	return xxx_messageInfo_IsEmailRegisteredRsp.Size(m)
}
func (m *IsEmailRegisteredRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRegisteredRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRegisteredRsp proto.InternalMessageInfo

func (m *IsEmailRegisteredRsp) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

type CreateUserReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *CreateUserReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserRsp struct {
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRsp) Reset()         { *m = CreateUserRsp{} }
func (m *CreateUserRsp) String() string { return proto.CompactTextString(m) }
func (*CreateUserRsp) ProtoMessage()    {}
func (*CreateUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRsp.Unmarshal(m, b)
}
func (m *CreateUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRsp.Marshal(b, m, deterministic)
}
func (m *CreateUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRsp.Merge(m, src)
}
func (m *CreateUserRsp) XXX_Size() int {
	return xxx_messageInfo_CreateUserRsp.Size(m)
}
func (m *CreateUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRsp proto.InternalMessageInfo

func (m *CreateUserRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type VerifyUserReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserReq) Reset()         { *m = VerifyUserReq{} }
func (m *VerifyUserReq) String() string { return proto.CompactTextString(m) }
func (*VerifyUserReq) ProtoMessage()    {}
func (*VerifyUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *VerifyUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserReq.Unmarshal(m, b)
}
func (m *VerifyUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserReq.Marshal(b, m, deterministic)
}
func (m *VerifyUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserReq.Merge(m, src)
}
func (m *VerifyUserReq) XXX_Size() int {
	return xxx_messageInfo_VerifyUserReq.Size(m)
}
func (m *VerifyUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserReq proto.InternalMessageInfo

func (m *VerifyUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type BaseUserInfo struct {
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseUserInfo) Reset()         { *m = BaseUserInfo{} }
func (m *BaseUserInfo) String() string { return proto.CompactTextString(m) }
func (*BaseUserInfo) ProtoMessage()    {}
func (*BaseUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *BaseUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseUserInfo.Unmarshal(m, b)
}
func (m *BaseUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseUserInfo.Marshal(b, m, deterministic)
}
func (m *BaseUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseUserInfo.Merge(m, src)
}
func (m *BaseUserInfo) XXX_Size() int {
	return xxx_messageInfo_BaseUserInfo.Size(m)
}
func (m *BaseUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseUserInfo proto.InternalMessageInfo

func (m *BaseUserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BaseUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *BaseUserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *BaseUserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type VerifyUserRsp struct {
	Result               VerifyUserRsp_Result `protobuf:"varint,1,opt,name=result,proto3,enum=user.VerifyUserRsp_Result" json:"result,omitempty"`
	UserInfo             *BaseUserInfo        `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VerifyUserRsp) Reset()         { *m = VerifyUserRsp{} }
func (m *VerifyUserRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyUserRsp) ProtoMessage()    {}
func (*VerifyUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *VerifyUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserRsp.Unmarshal(m, b)
}
func (m *VerifyUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserRsp.Marshal(b, m, deterministic)
}
func (m *VerifyUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserRsp.Merge(m, src)
}
func (m *VerifyUserRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyUserRsp.Size(m)
}
func (m *VerifyUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserRsp proto.InternalMessageInfo

func (m *VerifyUserRsp) GetResult() VerifyUserRsp_Result {
	if m != nil {
		return m.Result
	}
	return VerifyUserRsp_OK
}

func (m *VerifyUserRsp) GetUserInfo() *BaseUserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type UpdateUserLoginDateReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserLoginDateReq) Reset()         { *m = UpdateUserLoginDateReq{} }
func (m *UpdateUserLoginDateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserLoginDateReq) ProtoMessage()    {}
func (*UpdateUserLoginDateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UpdateUserLoginDateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserLoginDateReq.Unmarshal(m, b)
}
func (m *UpdateUserLoginDateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserLoginDateReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserLoginDateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserLoginDateReq.Merge(m, src)
}
func (m *UpdateUserLoginDateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserLoginDateReq.Size(m)
}
func (m *UpdateUserLoginDateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserLoginDateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserLoginDateReq proto.InternalMessageInfo

func (m *UpdateUserLoginDateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateUserLoginDateRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserLoginDateRsp) Reset()         { *m = UpdateUserLoginDateRsp{} }
func (m *UpdateUserLoginDateRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserLoginDateRsp) ProtoMessage()    {}
func (*UpdateUserLoginDateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UpdateUserLoginDateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserLoginDateRsp.Unmarshal(m, b)
}
func (m *UpdateUserLoginDateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserLoginDateRsp.Marshal(b, m, deterministic)
}
func (m *UpdateUserLoginDateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserLoginDateRsp.Merge(m, src)
}
func (m *UpdateUserLoginDateRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserLoginDateRsp.Size(m)
}
func (m *UpdateUserLoginDateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserLoginDateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserLoginDateRsp proto.InternalMessageInfo

////////////////////////
type InviteReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteReq) Reset()         { *m = InviteReq{} }
func (m *InviteReq) String() string { return proto.CompactTextString(m) }
func (*InviteReq) ProtoMessage()    {}
func (*InviteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *InviteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteReq.Unmarshal(m, b)
}
func (m *InviteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteReq.Marshal(b, m, deterministic)
}
func (m *InviteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteReq.Merge(m, src)
}
func (m *InviteReq) XXX_Size() int {
	return xxx_messageInfo_InviteReq.Size(m)
}
func (m *InviteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteReq.DiscardUnknown(m)
}

var xxx_messageInfo_InviteReq proto.InternalMessageInfo

func (m *InviteReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type InviteRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=user.Status" json:"status,omitempty"`
	InviteToken          string   `protobuf:"bytes,2,opt,name=invite_token,json=inviteToken,proto3" json:"invite_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteRsp) Reset()         { *m = InviteRsp{} }
func (m *InviteRsp) String() string { return proto.CompactTextString(m) }
func (*InviteRsp) ProtoMessage()    {}
func (*InviteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *InviteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteRsp.Unmarshal(m, b)
}
func (m *InviteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteRsp.Marshal(b, m, deterministic)
}
func (m *InviteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteRsp.Merge(m, src)
}
func (m *InviteRsp) XXX_Size() int {
	return xxx_messageInfo_InviteRsp.Size(m)
}
func (m *InviteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_InviteRsp proto.InternalMessageInfo

func (m *InviteRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *InviteRsp) GetInviteToken() string {
	if m != nil {
		return m.InviteToken
	}
	return ""
}

type RegisterReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ImageUrl             string   `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterReq) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type RegisterRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=user.Status" json:"status,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRsp) Reset()         { *m = RegisterRsp{} }
func (m *RegisterRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterRsp) ProtoMessage()    {}
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *RegisterRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRsp.Unmarshal(m, b)
}
func (m *RegisterRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRsp.Marshal(b, m, deterministic)
}
func (m *RegisterRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRsp.Merge(m, src)
}
func (m *RegisterRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterRsp.Size(m)
}
func (m *RegisterRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRsp proto.InternalMessageInfo

func (m *RegisterRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *RegisterRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type LoginReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=user.Status" json:"status,omitempty"`
	AuthToken            string   `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *LoginRsp) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type LogoutReq struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type LogoutRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=user.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRsp) Reset()         { *m = LogoutRsp{} }
func (m *LogoutRsp) String() string { return proto.CompactTextString(m) }
func (*LogoutRsp) ProtoMessage()    {}
func (*LogoutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *LogoutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRsp.Unmarshal(m, b)
}
func (m *LogoutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRsp.Marshal(b, m, deterministic)
}
func (m *LogoutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRsp.Merge(m, src)
}
func (m *LogoutRsp) XXX_Size() int {
	return xxx_messageInfo_LogoutRsp.Size(m)
}
func (m *LogoutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRsp proto.InternalMessageInfo

func (m *LogoutRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func init() {
	proto.RegisterEnum("user.Status", Status_name, Status_value)
	proto.RegisterEnum("user.VerifyUserRsp_Result", VerifyUserRsp_Result_name, VerifyUserRsp_Result_value)
	proto.RegisterType((*IsEmailRegisteredReq)(nil), "user.IsEmailRegisteredReq")
	proto.RegisterType((*IsEmailRegisteredRsp)(nil), "user.IsEmailRegisteredRsp")
	proto.RegisterType((*CreateUserReq)(nil), "user.CreateUserReq")
	proto.RegisterType((*CreateUserRsp)(nil), "user.CreateUserRsp")
	proto.RegisterType((*VerifyUserReq)(nil), "user.VerifyUserReq")
	proto.RegisterType((*BaseUserInfo)(nil), "user.BaseUserInfo")
	proto.RegisterType((*VerifyUserRsp)(nil), "user.VerifyUserRsp")
	proto.RegisterType((*UpdateUserLoginDateReq)(nil), "user.UpdateUserLoginDateReq")
	proto.RegisterType((*UpdateUserLoginDateRsp)(nil), "user.UpdateUserLoginDateRsp")
	proto.RegisterType((*InviteReq)(nil), "user.InviteReq")
	proto.RegisterType((*InviteRsp)(nil), "user.InviteRsp")
	proto.RegisterType((*RegisterReq)(nil), "user.RegisterReq")
	proto.RegisterType((*RegisterRsp)(nil), "user.RegisterRsp")
	proto.RegisterType((*LoginReq)(nil), "user.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "user.LoginRsp")
	proto.RegisterType((*LogoutReq)(nil), "user.LogoutReq")
	proto.RegisterType((*LogoutRsp)(nil), "user.LogoutRsp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 724 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0xf3, 0xe3, 0xc6, 0xd3, 0xa4, 0x75, 0xa7, 0x55, 0x89, 0xcc, 0x8f, 0xa8, 0xc5, 0xa1,
	0x54, 0x55, 0x50, 0x83, 0x84, 0x38, 0x70, 0x01, 0x1a, 0x50, 0x44, 0x69, 0x2a, 0x27, 0xa5, 0xdc,
	0xa2, 0x2d, 0xde, 0x06, 0xab, 0x8e, 0xed, 0x7a, 0xed, 0x42, 0xdf, 0x02, 0x90, 0x78, 0x03, 0x8e,
	0xfc, 0xbc, 0x06, 0xaf, 0xc0, 0xdb, 0xa0, 0xdd, 0xb5, 0x93, 0x38, 0x75, 0xaa, 0xaa, 0x37, 0xcf,
	0x37, 0xdf, 0xec, 0xfc, 0x8f, 0x01, 0x62, 0x46, 0xc3, 0x66, 0x10, 0xfa, 0x91, 0x8f, 0x65, 0xfe,
	0x6d, 0x6e, 0xc3, 0x5a, 0x87, 0xb5, 0x47, 0xc4, 0x71, 0x2d, 0x3a, 0x74, 0x58, 0x44, 0x43, 0x6a,
	0x5b, 0xf4, 0x0c, 0xd7, 0xa0, 0x42, 0x39, 0xda, 0x50, 0xee, 0x2b, 0x9b, 0x9a, 0x25, 0x05, 0xf3,
	0x49, 0x1e, 0x9b, 0x05, 0x78, 0x0f, 0x20, 0x1c, 0x03, 0xc2, 0xa4, 0x6a, 0x4d, 0x21, 0x66, 0x0c,
	0xf5, 0x97, 0x21, 0x25, 0x11, 0x3d, 0x64, 0x34, 0x9c, 0xfb, 0x3c, 0xae, 0x83, 0x4a, 0xce, 0x49,
	0x44, 0xc2, 0x46, 0x51, 0xc0, 0x89, 0x84, 0x06, 0x54, 0x3d, 0xe7, 0xc3, 0xa9, 0x47, 0x46, 0xb4,
	0x51, 0x12, 0x9a, 0xb1, 0xcc, 0x75, 0x01, 0x61, 0xec, 0x93, 0x1f, 0xda, 0x8d, 0xb2, 0xd4, 0xa5,
	0xb2, 0xb9, 0x99, 0x71, 0xcb, 0x02, 0xbc, 0x05, 0x0b, 0x3c, 0xeb, 0x81, 0x63, 0x0b, 0x0f, 0x25,
	0x4b, 0xe5, 0x62, 0xc7, 0x36, 0x9f, 0x43, 0xfd, 0x1d, 0x0d, 0x9d, 0x93, 0x8b, 0xab, 0x03, 0x9c,
	0x76, 0x56, 0x9c, 0x71, 0x76, 0x06, 0xb5, 0x17, 0x84, 0x09, 0x57, 0x1d, 0xef, 0xc4, 0x9f, 0xeb,
	0x6b, 0xf2, 0x74, 0x29, 0x3f, 0xf7, 0xf2, 0xdc, 0xdc, 0x2b, 0xd9, 0xdc, 0xcd, 0x1f, 0x4a, 0x26,
	0x6c, 0x16, 0x60, 0x0b, 0xd4, 0x90, 0xb2, 0xd8, 0x8d, 0x44, 0xdc, 0x4b, 0x2d, 0xa3, 0x29, 0x3a,
	0x9e, 0x21, 0x35, 0x2d, 0xc1, 0xb0, 0x12, 0x26, 0x3e, 0x02, 0x4d, 0x06, 0xea, 0x9d, 0xf8, 0x22,
	0xd4, 0xc5, 0x16, 0x4a, 0xb3, 0xe9, 0x7c, 0xac, 0x6a, 0x9c, 0x7c, 0x99, 0x4d, 0x50, 0xe5, 0x13,
	0xa8, 0x42, 0xb1, 0xfb, 0x46, 0x2f, 0x60, 0x1d, 0xb4, 0xfd, 0x6e, 0x7f, 0xd0, 0x7e, 0xdf, 0xe9,
	0xf5, 0x75, 0x85, 0x8b, 0x07, 0x47, 0xbb, 0x83, 0x23, 0xab, 0xbb, 0xff, 0x5a, 0x2f, 0x9a, 0x3b,
	0xb0, 0x7e, 0x18, 0xd8, 0x49, 0x1b, 0xf6, 0xfc, 0xa1, 0xe3, 0xed, 0x92, 0x88, 0xf2, 0x2a, 0x4f,
	0xd5, 0x48, 0xc9, 0xf4, 0xa3, 0x91, 0x6f, 0xc2, 0x02, 0x73, 0x03, 0xb4, 0x8e, 0x77, 0xee, 0x48,
	0xfb, 0xfc, 0x29, 0xed, 0x8f, 0x29, 0x2c, 0xc0, 0x07, 0xa0, 0xb2, 0x88, 0x44, 0x31, 0x4b, 0x2a,
	0x52, 0x93, 0xa9, 0xf5, 0x04, 0x66, 0x25, 0x3a, 0xdc, 0x80, 0x9a, 0x23, 0x4c, 0x06, 0x91, 0x7f,
	0x4a, 0xbd, 0xa4, 0xb9, 0x8b, 0x12, 0xeb, 0x73, 0xc8, 0xfc, 0xa2, 0xc0, 0x62, 0x3a, 0xf5, 0x37,
	0x9a, 0x10, 0xde, 0xe2, 0x91, 0x7f, 0xec, 0xb8, 0x34, 0x6d, 0xb1, 0x94, 0xae, 0x6a, 0x31, 0xde,
	0x06, 0xcd, 0x19, 0x91, 0x21, 0x1d, 0xc4, 0xa1, 0xdb, 0x50, 0xa5, 0x52, 0x00, 0x87, 0xa1, 0x6b,
	0xee, 0x4d, 0x45, 0x74, 0xed, 0x54, 0xe7, 0xee, 0xc0, 0x33, 0xa8, 0x8a, 0x4a, 0xdf, 0x6c, 0xfc,
	0xbb, 0xa9, 0xf5, 0xb5, 0x03, 0xb9, 0x0b, 0x40, 0xe2, 0xe8, 0x63, 0xa6, 0xe2, 0x1a, 0x47, 0x64,
	0xbd, 0xb7, 0x40, 0xdb, 0xf3, 0x87, 0x7e, 0x1c, 0xf1, 0x78, 0xb2, 0x5c, 0x65, 0x96, 0xbb, 0x33,
	0xe6, 0x5e, 0xd7, 0xfb, 0xd6, 0x77, 0x05, 0x54, 0x09, 0xa1, 0x06, 0x95, 0xf6, 0x28, 0x88, 0x2e,
	0xf4, 0x02, 0x2e, 0x88, 0x81, 0xfe, 0xab, 0xe0, 0x0a, 0xd4, 0x0e, 0x48, 0x48, 0x46, 0x1d, 0xef,
	0x9c, 0xb8, 0x8e, 0xad, 0xff, 0x2c, 0x72, 0x48, 0x9c, 0xbe, 0x14, 0xfa, 0x55, 0xc4, 0x35, 0x58,
	0x9e, 0xb9, 0x86, 0xfa, 0xef, 0x09, 0xda, 0xa3, 0x9e, 0xfd, 0x8a, 0x38, 0x2e, 0xb5, 0xf5, 0x3f,
	0xc2, 0x9c, 0x0f, 0xf3, 0xbe, 0x1f, 0xb5, 0x3f, 0x3b, 0x2c, 0xd2, 0xbf, 0x96, 0x10, 0xa1, 0x7e,
	0x90, 0xd4, 0xef, 0x28, 0xf4, 0xbd, 0xa1, 0xfe, 0xad, 0xd4, 0xfa, 0x57, 0x82, 0x32, 0xe7, 0xe1,
	0x5b, 0x58, 0xb9, 0x74, 0x6b, 0x31, 0xd9, 0xe7, 0xbc, 0x93, 0x6d, 0xcc, 0xd5, 0xb1, 0xc0, 0x2c,
	0xe0, 0x53, 0x80, 0xc9, 0x2d, 0xc4, 0x55, 0xc9, 0xcd, 0x1c, 0x65, 0xe3, 0x32, 0x98, 0x5a, 0x4e,
	0xee, 0x47, 0x6a, 0x99, 0xb9, 0x96, 0xc6, 0x6a, 0xce, 0x99, 0x31, 0x0b, 0xd8, 0x83, 0xd5, 0x9c,
	0x2d, 0xc6, 0x3b, 0x92, 0x9d, 0x7f, 0x13, 0x8c, 0x2b, 0xb4, 0xe2, 0xd1, 0x6d, 0x50, 0xe5, 0x76,
	0xe3, 0x72, 0x92, 0x70, 0x7a, 0x0e, 0x8c, 0x2c, 0x20, 0xd8, 0x2d, 0xa8, 0xa6, 0x95, 0xc0, 0x15,
	0xa9, 0x9e, 0x5a, 0x62, 0x63, 0x16, 0x12, 0x36, 0x0f, 0xa1, 0x22, 0x7c, 0xe2, 0x92, 0xd4, 0xa6,
	0x5b, 0x61, 0x64, 0xe4, 0x34, 0x18, 0x39, 0x78, 0x69, 0x30, 0xe3, 0x91, 0x35, 0xb2, 0x00, 0x67,
	0x1f, 0xab, 0xe2, 0xcf, 0xfb, 0xf8, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x7a, 0xc9, 0x45,
	0x87, 0x07, 0x00, 0x00,
}
