// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserVerifyStatus int32

const (
	UserVerifyStatus_OK        UserVerifyStatus = 0
	UserVerifyStatus_NOT_EXIST UserVerifyStatus = 1
	UserVerifyStatus_PWD_ERROR UserVerifyStatus = 2
)

var UserVerifyStatus_name = map[int32]string{
	0: "OK",
	1: "NOT_EXIST",
	2: "PWD_ERROR",
}

var UserVerifyStatus_value = map[string]int32{
	"OK":        0,
	"NOT_EXIST": 1,
	"PWD_ERROR": 2,
}

func (x UserVerifyStatus) String() string {
	return proto.EnumName(UserVerifyStatus_name, int32(x))
}

func (UserVerifyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type IsEmailRegisteredReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRegisteredReq) Reset()         { *m = IsEmailRegisteredReq{} }
func (m *IsEmailRegisteredReq) String() string { return proto.CompactTextString(m) }
func (*IsEmailRegisteredReq) ProtoMessage()    {}
func (*IsEmailRegisteredReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *IsEmailRegisteredReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRegisteredReq.Unmarshal(m, b)
}
func (m *IsEmailRegisteredReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRegisteredReq.Marshal(b, m, deterministic)
}
func (m *IsEmailRegisteredReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRegisteredReq.Merge(m, src)
}
func (m *IsEmailRegisteredReq) XXX_Size() int {
	return xxx_messageInfo_IsEmailRegisteredReq.Size(m)
}
func (m *IsEmailRegisteredReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRegisteredReq.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRegisteredReq proto.InternalMessageInfo

func (m *IsEmailRegisteredReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type IsEmailRegisteredRsp struct {
	Registered           bool     `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsEmailRegisteredRsp) Reset()         { *m = IsEmailRegisteredRsp{} }
func (m *IsEmailRegisteredRsp) String() string { return proto.CompactTextString(m) }
func (*IsEmailRegisteredRsp) ProtoMessage()    {}
func (*IsEmailRegisteredRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *IsEmailRegisteredRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsEmailRegisteredRsp.Unmarshal(m, b)
}
func (m *IsEmailRegisteredRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsEmailRegisteredRsp.Marshal(b, m, deterministic)
}
func (m *IsEmailRegisteredRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsEmailRegisteredRsp.Merge(m, src)
}
func (m *IsEmailRegisteredRsp) XXX_Size() int {
	return xxx_messageInfo_IsEmailRegisteredRsp.Size(m)
}
func (m *IsEmailRegisteredRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IsEmailRegisteredRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IsEmailRegisteredRsp proto.InternalMessageInfo

func (m *IsEmailRegisteredRsp) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

type CreateNewUserReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewUserReq) Reset()         { *m = CreateNewUserReq{} }
func (m *CreateNewUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateNewUserReq) ProtoMessage()    {}
func (*CreateNewUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateNewUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewUserReq.Unmarshal(m, b)
}
func (m *CreateNewUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewUserReq.Marshal(b, m, deterministic)
}
func (m *CreateNewUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewUserReq.Merge(m, src)
}
func (m *CreateNewUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateNewUserReq.Size(m)
}
func (m *CreateNewUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewUserReq proto.InternalMessageInfo

func (m *CreateNewUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateNewUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateNewUserReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateNewUserReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type CreateNewUserRsp struct {
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewUserRsp) Reset()         { *m = CreateNewUserRsp{} }
func (m *CreateNewUserRsp) String() string { return proto.CompactTextString(m) }
func (*CreateNewUserRsp) ProtoMessage()    {}
func (*CreateNewUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateNewUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewUserRsp.Unmarshal(m, b)
}
func (m *CreateNewUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewUserRsp.Marshal(b, m, deterministic)
}
func (m *CreateNewUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewUserRsp.Merge(m, src)
}
func (m *CreateNewUserRsp) XXX_Size() int {
	return xxx_messageInfo_CreateNewUserRsp.Size(m)
}
func (m *CreateNewUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewUserRsp proto.InternalMessageInfo

func (m *CreateNewUserRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type VerifyUserReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyUserReq) Reset()         { *m = VerifyUserReq{} }
func (m *VerifyUserReq) String() string { return proto.CompactTextString(m) }
func (*VerifyUserReq) ProtoMessage()    {}
func (*VerifyUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *VerifyUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserReq.Unmarshal(m, b)
}
func (m *VerifyUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserReq.Marshal(b, m, deterministic)
}
func (m *VerifyUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserReq.Merge(m, src)
}
func (m *VerifyUserReq) XXX_Size() int {
	return xxx_messageInfo_VerifyUserReq.Size(m)
}
func (m *VerifyUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserReq proto.InternalMessageInfo

func (m *VerifyUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserInfo struct {
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type VerifyUserRsp struct {
	VerifyStatus         UserVerifyStatus `protobuf:"varint,1,opt,name=verify_status,json=verifyStatus,proto3,enum=proto.UserVerifyStatus" json:"verify_status,omitempty"`
	UserInfo             *UserInfo        `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *VerifyUserRsp) Reset()         { *m = VerifyUserRsp{} }
func (m *VerifyUserRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyUserRsp) ProtoMessage()    {}
func (*VerifyUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *VerifyUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyUserRsp.Unmarshal(m, b)
}
func (m *VerifyUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyUserRsp.Marshal(b, m, deterministic)
}
func (m *VerifyUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyUserRsp.Merge(m, src)
}
func (m *VerifyUserRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyUserRsp.Size(m)
}
func (m *VerifyUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyUserRsp proto.InternalMessageInfo

func (m *VerifyUserRsp) GetVerifyStatus() UserVerifyStatus {
	if m != nil {
		return m.VerifyStatus
	}
	return UserVerifyStatus_OK
}

func (m *VerifyUserRsp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type UpdateUserLoginDateReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserLoginDateReq) Reset()         { *m = UpdateUserLoginDateReq{} }
func (m *UpdateUserLoginDateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserLoginDateReq) ProtoMessage()    {}
func (*UpdateUserLoginDateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UpdateUserLoginDateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserLoginDateReq.Unmarshal(m, b)
}
func (m *UpdateUserLoginDateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserLoginDateReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserLoginDateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserLoginDateReq.Merge(m, src)
}
func (m *UpdateUserLoginDateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserLoginDateReq.Size(m)
}
func (m *UpdateUserLoginDateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserLoginDateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserLoginDateReq proto.InternalMessageInfo

func (m *UpdateUserLoginDateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateUserLoginDateRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserLoginDateRsp) Reset()         { *m = UpdateUserLoginDateRsp{} }
func (m *UpdateUserLoginDateRsp) String() string { return proto.CompactTextString(m) }
func (*UpdateUserLoginDateRsp) ProtoMessage()    {}
func (*UpdateUserLoginDateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UpdateUserLoginDateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserLoginDateRsp.Unmarshal(m, b)
}
func (m *UpdateUserLoginDateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserLoginDateRsp.Marshal(b, m, deterministic)
}
func (m *UpdateUserLoginDateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserLoginDateRsp.Merge(m, src)
}
func (m *UpdateUserLoginDateRsp) XXX_Size() int {
	return xxx_messageInfo_UpdateUserLoginDateRsp.Size(m)
}
func (m *UpdateUserLoginDateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserLoginDateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserLoginDateRsp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.UserVerifyStatus", UserVerifyStatus_name, UserVerifyStatus_value)
	proto.RegisterType((*IsEmailRegisteredReq)(nil), "proto.IsEmailRegisteredReq")
	proto.RegisterType((*IsEmailRegisteredRsp)(nil), "proto.IsEmailRegisteredRsp")
	proto.RegisterType((*CreateNewUserReq)(nil), "proto.CreateNewUserReq")
	proto.RegisterType((*CreateNewUserRsp)(nil), "proto.CreateNewUserRsp")
	proto.RegisterType((*VerifyUserReq)(nil), "proto.VerifyUserReq")
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*VerifyUserRsp)(nil), "proto.VerifyUserRsp")
	proto.RegisterType((*UpdateUserLoginDateReq)(nil), "proto.UpdateUserLoginDateReq")
	proto.RegisterType((*UpdateUserLoginDateRsp)(nil), "proto.UpdateUserLoginDateRsp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0x9c, 0xc6, 0x38, 0x03, 0x06, 0x33, 0x44, 0xad, 0x65, 0x04, 0x42, 0x7b, 0x42, 0x50,
	0x55, 0x22, 0x48, 0x08, 0x21, 0x2e, 0xa8, 0xcd, 0xc1, 0x02, 0xd5, 0x68, 0xdb, 0x00, 0x37, 0x6b,
	0xc1, 0x9b, 0xca, 0x82, 0xd8, 0xcb, 0xee, 0x26, 0x05, 0xf1, 0xa3, 0xf8, 0x8b, 0x68, 0xd7, 0x4e,
	0x63, 0x07, 0x9b, 0x03, 0x27, 0xfb, 0xcd, 0xdb, 0x37, 0xf3, 0xe6, 0x03, 0x60, 0xa5, 0xb8, 0x3c,
	0x16, 0xb2, 0xd4, 0x25, 0x8e, 0xec, 0x87, 0x1c, 0xc1, 0x24, 0x56, 0xb3, 0x25, 0xcb, 0xbf, 0x51,
	0x7e, 0x99, 0x2b, 0xcd, 0x25, 0xcf, 0x28, 0xff, 0x8e, 0x13, 0x18, 0x71, 0x13, 0x0d, 0x07, 0x8f,
	0x06, 0x8f, 0xc7, 0xb4, 0x02, 0xe4, 0x45, 0xd7, 0x6b, 0x25, 0xf0, 0x21, 0x80, 0xbc, 0x0e, 0x58,
	0x89, 0x47, 0x1b, 0x11, 0xf2, 0x03, 0x82, 0x13, 0xc9, 0x99, 0xe6, 0x67, 0xfc, 0x6a, 0xae, 0xb8,
	0xec, 0xad, 0x80, 0x11, 0x78, 0x82, 0x29, 0x75, 0x55, 0xca, 0x2c, 0x74, 0x2c, 0x71, 0x8d, 0x0d,
	0x57, 0xe4, 0x5f, 0xbe, 0x16, 0x6c, 0xc9, 0xc3, 0x61, 0xc5, 0x6d, 0x30, 0x1e, 0x80, 0xcb, 0xd6,
	0x4c, 0x33, 0x19, 0xee, 0x5b, 0xa6, 0x46, 0xe4, 0xe9, 0x6e, 0x65, 0x25, 0xf0, 0x10, 0x6e, 0x98,
	0x41, 0xa4, 0x79, 0x55, 0x62, 0x48, 0x5d, 0x03, 0xe3, 0x8c, 0xbc, 0x01, 0xff, 0x03, 0x97, 0xf9,
	0xe2, 0xe7, 0x7f, 0x7b, 0x24, 0x4b, 0xf0, 0x8c, 0x38, 0x2e, 0x16, 0x65, 0x6f, 0x9d, 0x6d, 0xda,
	0x61, 0x33, 0x6d, 0x4f, 0x0b, 0xad, 0xb6, 0x47, 0xed, 0xb6, 0xc9, 0xaf, 0x96, 0x63, 0x25, 0xf0,
	0x35, 0xf8, 0x6b, 0x1b, 0x48, 0x95, 0x66, 0x7a, 0xa5, 0xac, 0xf3, 0xdb, 0xd3, 0xc3, 0x6a, 0xeb,
	0xc7, 0xe6, 0x59, 0x25, 0x38, 0xb7, 0x34, 0xbd, 0xb5, 0x6e, 0x20, 0x3c, 0x82, 0x71, 0xe5, 0xb8,
	0x58, 0x94, 0xd6, 0xf3, 0xcd, 0xe9, 0x9d, 0x86, 0xd2, 0x74, 0x45, 0xbd, 0x55, 0xfd, 0x47, 0x9e,
	0xc1, 0xc1, 0x5c, 0x64, 0x4c, 0x73, 0xc3, 0xbd, 0x2b, 0x2f, 0xf3, 0xe2, 0x94, 0x69, 0x6e, 0xe6,
	0xd6, 0xe8, 0x7c, 0xd0, 0x9a, 0x70, 0xd8, 0x2d, 0x51, 0xe2, 0xc9, 0x4b, 0x08, 0x76, 0xcd, 0xa1,
	0x0b, 0x4e, 0xf2, 0x36, 0xd8, 0x43, 0x1f, 0xc6, 0x67, 0xc9, 0x45, 0x3a, 0xfb, 0x14, 0x9f, 0x5f,
	0x04, 0x03, 0x03, 0xdf, 0x7f, 0x3c, 0x4d, 0x67, 0x94, 0x26, 0x34, 0x70, 0xa6, 0xbf, 0x1d, 0xd8,
	0x37, 0x52, 0x4c, 0xe0, 0xee, 0x5f, 0xd7, 0x89, 0xf7, 0x6b, 0xff, 0x5d, 0x57, 0x1e, 0xf5, 0x93,
	0x4a, 0x90, 0x3d, 0x3c, 0x01, 0xbf, 0x75, 0x3c, 0xb8, 0x19, 0xe3, 0xee, 0x31, 0x47, 0xdd, 0x84,
	0x4d, 0xf2, 0x0a, 0x60, 0xbb, 0x22, 0x9c, 0xd4, 0x0f, 0x5b, 0x77, 0x16, 0x75, 0x44, 0xad, 0x76,
	0x0e, 0xf7, 0x3a, 0xc6, 0x85, 0x0f, 0x36, 0x3b, 0xe9, 0x9c, 0x7e, 0xf4, 0x2f, 0xda, 0xa4, 0xfd,
	0xec, 0x5a, 0xfe, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xde, 0x75, 0x78, 0x10, 0x04,
	0x00, 0x00,
}
