// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartEmailReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartEmailReq) Reset()         { *m = StartEmailReq{} }
func (m *StartEmailReq) String() string { return proto.CompactTextString(m) }
func (*StartEmailReq) ProtoMessage()    {}
func (*StartEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *StartEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartEmailReq.Unmarshal(m, b)
}
func (m *StartEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartEmailReq.Marshal(b, m, deterministic)
}
func (m *StartEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartEmailReq.Merge(m, src)
}
func (m *StartEmailReq) XXX_Size() int {
	return xxx_messageInfo_StartEmailReq.Size(m)
}
func (m *StartEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartEmailReq proto.InternalMessageInfo

func (m *StartEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type StartEmailRsp struct {
	SignUpToken          string   `protobuf:"bytes,1,opt,name=sign_up_token,json=signUpToken,proto3" json:"sign_up_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartEmailRsp) Reset()         { *m = StartEmailRsp{} }
func (m *StartEmailRsp) String() string { return proto.CompactTextString(m) }
func (*StartEmailRsp) ProtoMessage()    {}
func (*StartEmailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *StartEmailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartEmailRsp.Unmarshal(m, b)
}
func (m *StartEmailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartEmailRsp.Marshal(b, m, deterministic)
}
func (m *StartEmailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartEmailRsp.Merge(m, src)
}
func (m *StartEmailRsp) XXX_Size() int {
	return xxx_messageInfo_StartEmailRsp.Size(m)
}
func (m *StartEmailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartEmailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_StartEmailRsp proto.InternalMessageInfo

func (m *StartEmailRsp) GetSignUpToken() string {
	if m != nil {
		return m.SignUpToken
	}
	return ""
}

type User struct {
	Id                      int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName                string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password                string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	PasswordSalt            string   `protobuf:"bytes,4,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	Mobile                  string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                   string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	IsApproved              int32    `protobuf:"varint,7,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	IsLocked                int32    `protobuf:"varint,8,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	LastLoginDate           string   `protobuf:"bytes,9,opt,name=last_login_date,json=lastLoginDate,proto3" json:"last_login_date,omitempty"`
	LastPasswordChangedDate string   `protobuf:"bytes,10,opt,name=last_password_changed_date,json=lastPasswordChangedDate,proto3" json:"last_password_changed_date,omitempty"`
	LastLockoutDate         string   `protobuf:"bytes,11,opt,name=last_lockout_date,json=lastLockoutDate,proto3" json:"last_lockout_date,omitempty"`
	Remark                  string   `protobuf:"bytes,12,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedOn               string   `protobuf:"bytes,13,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn               string   `protobuf:"bytes,14,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetPasswordSalt() string {
	if m != nil {
		return m.PasswordSalt
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsApproved() int32 {
	if m != nil {
		return m.IsApproved
	}
	return 0
}

func (m *User) GetIsLocked() int32 {
	if m != nil {
		return m.IsLocked
	}
	return 0
}

func (m *User) GetLastLoginDate() string {
	if m != nil {
		return m.LastLoginDate
	}
	return ""
}

func (m *User) GetLastPasswordChangedDate() string {
	if m != nil {
		return m.LastPasswordChangedDate
	}
	return ""
}

func (m *User) GetLastLockoutDate() string {
	if m != nil {
		return m.LastLockoutDate
	}
	return ""
}

func (m *User) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *User) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *User) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

type SignUpReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignUpRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRsp) Reset()         { *m = SignUpRsp{} }
func (m *SignUpRsp) String() string { return proto.CompactTextString(m) }
func (*SignUpRsp) ProtoMessage()    {}
func (*SignUpRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *SignUpRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRsp.Unmarshal(m, b)
}
func (m *SignUpRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRsp.Marshal(b, m, deterministic)
}
func (m *SignUpRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRsp.Merge(m, src)
}
func (m *SignUpRsp) XXX_Size() int {
	return xxx_messageInfo_SignUpRsp.Size(m)
}
func (m *SignUpRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRsp proto.InternalMessageInfo

func (m *SignUpRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*StartEmailReq)(nil), "proto.StartEmailReq")
	proto.RegisterType((*StartEmailRsp)(nil), "proto.StartEmailRsp")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*SignUpReq)(nil), "proto.SignUpReq")
	proto.RegisterType((*SignUpRsp)(nil), "proto.SignUpRsp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcb, 0x6f, 0xd4, 0x30,
	0x10, 0xc6, 0xd9, 0x57, 0x76, 0x33, 0x69, 0x5a, 0xb0, 0xaa, 0xd6, 0x5a, 0x84, 0x5a, 0x85, 0x87,
	0x2a, 0x84, 0xf6, 0xd0, 0xde, 0xe0, 0x84, 0x80, 0x03, 0x52, 0x45, 0x51, 0x96, 0x9e, 0x2d, 0x77,
	0x6d, 0x2d, 0x56, 0x1e, 0x36, 0xb6, 0x53, 0xfe, 0x44, 0xfe, 0x2d, 0xe4, 0x71, 0xb2, 0x65, 0x51,
	0x4f, 0xc9, 0xfc, 0xbe, 0xef, 0xb3, 0xc7, 0x9a, 0x01, 0xe8, 0x9c, 0xb4, 0x2b, 0x63, 0xb5, 0xd7,
	0x64, 0x86, 0x9f, 0xe2, 0x35, 0xe4, 0x6b, 0xcf, 0xad, 0xff, 0xd2, 0x70, 0x55, 0x97, 0xf2, 0x17,
	0x39, 0x86, 0x99, 0x0c, 0xff, 0x74, 0x74, 0x3e, 0xba, 0x48, 0xcb, 0x58, 0x14, 0x57, 0x7b, 0x36,
	0x67, 0x48, 0x01, 0xb9, 0x53, 0xdb, 0x96, 0x75, 0x86, 0x79, 0x5d, 0xc9, 0xb6, 0xb7, 0x67, 0x01,
	0xde, 0x9a, 0x1f, 0x01, 0x15, 0x7f, 0x26, 0x30, 0xbd, 0x75, 0xd2, 0x92, 0x43, 0x18, 0x2b, 0x81,
	0x8e, 0x49, 0x39, 0x56, 0x82, 0x3c, 0x87, 0x34, 0x74, 0xc2, 0x5a, 0xde, 0x48, 0x3a, 0xc6, 0xe0,
	0x22, 0x80, 0x6f, 0xbc, 0x91, 0x64, 0x09, 0x0b, 0xc3, 0x9d, 0xfb, 0xad, 0xad, 0xa0, 0x93, 0xa8,
	0x0d, 0x35, 0x79, 0x09, 0xf9, 0xf0, 0xcf, 0x1c, 0xaf, 0x3d, 0x9d, 0xa2, 0xe1, 0x60, 0x80, 0x6b,
	0x5e, 0x7b, 0x72, 0x02, 0x49, 0xa3, 0xef, 0x54, 0x2d, 0xe9, 0x0c, 0xd5, 0xbe, 0x7a, 0x78, 0x59,
	0xf2, 0xcf, 0xcb, 0xc8, 0x19, 0x64, 0xca, 0x31, 0x6e, 0x8c, 0xd5, 0xf7, 0x52, 0xd0, 0xf9, 0xf9,
	0xe8, 0x62, 0x56, 0x82, 0x72, 0x1f, 0x7b, 0x12, 0x9a, 0x55, 0x8e, 0xd5, 0x7a, 0x53, 0x49, 0x41,
	0x17, 0x28, 0x2f, 0x94, 0xbb, 0xc6, 0x9a, 0xbc, 0x81, 0xa3, 0x9a, 0x3b, 0xcf, 0x6a, 0xbd, 0x55,
	0x2d, 0x13, 0xdc, 0x4b, 0x9a, 0xe2, 0xe9, 0x79, 0xc0, 0xd7, 0x81, 0x7e, 0xe6, 0x5e, 0x92, 0x0f,
	0xb0, 0x44, 0xdf, 0xae, 0xfb, 0xcd, 0x4f, 0xde, 0x6e, 0xa5, 0x88, 0x11, 0xc0, 0xc8, 0x69, 0x70,
	0x7c, 0xef, 0x0d, 0x9f, 0xa2, 0x8e, 0xe1, 0xb7, 0xf0, 0xac, 0xbf, 0x64, 0x53, 0xe9, 0xce, 0xc7,
	0x4c, 0x86, 0x99, 0xa3, 0x78, 0x0d, 0x72, 0xf4, 0x9e, 0x40, 0x62, 0x65, 0xc3, 0x6d, 0x45, 0x0f,
	0xe2, 0xe3, 0x63, 0x45, 0x5e, 0x00, 0x6c, 0xac, 0xe4, 0x5e, 0x0a, 0xa6, 0x5b, 0x9a, 0xa3, 0x96,
	0xf6, 0xe4, 0xa6, 0x0d, 0x72, 0x67, 0xc4, 0x20, 0x1f, 0x46, 0xb9, 0x27, 0x37, 0x6d, 0xf1, 0x0e,
	0xd2, 0x35, 0x0e, 0x36, 0x6c, 0xc8, 0x19, 0x4c, 0xc3, 0xb0, 0x70, 0x9e, 0xd9, 0x65, 0x16, 0xf7,
	0x69, 0x15, 0x06, 0x5d, 0xa2, 0x50, 0xbc, 0xda, 0xb9, 0x9d, 0x21, 0xa7, 0x30, 0xc7, 0x59, 0xef,
	0x16, 0x20, 0x09, 0xe5, 0x57, 0x71, 0xd9, 0xc1, 0x3c, 0x64, 0xd6, 0xf6, 0x9e, 0xbc, 0x07, 0x78,
	0xd8, 0x2e, 0x72, 0xdc, 0x9f, 0xb8, 0xb7, 0x97, 0xcb, 0x47, 0xa8, 0x33, 0xc5, 0x13, 0xb2, 0x82,
	0x24, 0x5e, 0x46, 0x9e, 0x0e, 0x8e, 0xa1, 0xd3, 0xe5, 0x7f, 0x24, 0xf8, 0xef, 0x12, 0x44, 0x57,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x89, 0xa1, 0xfa, 0x64, 0x0c, 0x03, 0x00, 0x00,
}
