// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenStatus int32

const (
	TokenStatus_OK       TokenStatus = 0
	TokenStatus_INVALID  TokenStatus = 1
	TokenStatus_EXPIRED  TokenStatus = 2
	TokenStatus_CANCELED TokenStatus = 3
)

var TokenStatus_name = map[int32]string{
	0: "OK",
	1: "INVALID",
	2: "EXPIRED",
	3: "CANCELED",
}

var TokenStatus_value = map[string]int32{
	"OK":       0,
	"INVALID":  1,
	"EXPIRED":  2,
	"CANCELED": 3,
}

func (x TokenStatus) String() string {
	return proto.EnumName(TokenStatus_name, int32(x))
}

func (TokenStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

type RegisterTokenClaims struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTokenClaims) Reset()         { *m = RegisterTokenClaims{} }
func (m *RegisterTokenClaims) String() string { return proto.CompactTextString(m) }
func (*RegisterTokenClaims) ProtoMessage()    {}
func (*RegisterTokenClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *RegisterTokenClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTokenClaims.Unmarshal(m, b)
}
func (m *RegisterTokenClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTokenClaims.Marshal(b, m, deterministic)
}
func (m *RegisterTokenClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTokenClaims.Merge(m, src)
}
func (m *RegisterTokenClaims) XXX_Size() int {
	return xxx_messageInfo_RegisterTokenClaims.Size(m)
}
func (m *RegisterTokenClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTokenClaims.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTokenClaims proto.InternalMessageInfo

func (m *RegisterTokenClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterTokenClaims) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type GetRegisterTokenReq struct {
	Claims               *RegisterTokenClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	SecretKey            string               `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetRegisterTokenReq) Reset()         { *m = GetRegisterTokenReq{} }
func (m *GetRegisterTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetRegisterTokenReq) ProtoMessage()    {}
func (*GetRegisterTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{1}
}

func (m *GetRegisterTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRegisterTokenReq.Unmarshal(m, b)
}
func (m *GetRegisterTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRegisterTokenReq.Marshal(b, m, deterministic)
}
func (m *GetRegisterTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegisterTokenReq.Merge(m, src)
}
func (m *GetRegisterTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetRegisterTokenReq.Size(m)
}
func (m *GetRegisterTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegisterTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegisterTokenReq proto.InternalMessageInfo

func (m *GetRegisterTokenReq) GetClaims() *RegisterTokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *GetRegisterTokenReq) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type GetRegisterTokenRsp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRegisterTokenRsp) Reset()         { *m = GetRegisterTokenRsp{} }
func (m *GetRegisterTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetRegisterTokenRsp) ProtoMessage()    {}
func (*GetRegisterTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{2}
}

func (m *GetRegisterTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRegisterTokenRsp.Unmarshal(m, b)
}
func (m *GetRegisterTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRegisterTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetRegisterTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRegisterTokenRsp.Merge(m, src)
}
func (m *GetRegisterTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetRegisterTokenRsp.Size(m)
}
func (m *GetRegisterTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRegisterTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRegisterTokenRsp proto.InternalMessageInfo

func (m *GetRegisterTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyRegisterTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRegisterTokenReq) Reset()         { *m = VerifyRegisterTokenReq{} }
func (m *VerifyRegisterTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyRegisterTokenReq) ProtoMessage()    {}
func (*VerifyRegisterTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{3}
}

func (m *VerifyRegisterTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRegisterTokenReq.Unmarshal(m, b)
}
func (m *VerifyRegisterTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRegisterTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyRegisterTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRegisterTokenReq.Merge(m, src)
}
func (m *VerifyRegisterTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyRegisterTokenReq.Size(m)
}
func (m *VerifyRegisterTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRegisterTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRegisterTokenReq proto.InternalMessageInfo

func (m *VerifyRegisterTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifyRegisterTokenReq) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type VerifyRegisterTokenRsp struct {
	TokenStatus          TokenStatus          `protobuf:"varint,1,opt,name=token_status,json=tokenStatus,proto3,enum=proto.TokenStatus" json:"token_status,omitempty"`
	Claims               *RegisterTokenClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VerifyRegisterTokenRsp) Reset()         { *m = VerifyRegisterTokenRsp{} }
func (m *VerifyRegisterTokenRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyRegisterTokenRsp) ProtoMessage()    {}
func (*VerifyRegisterTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{4}
}

func (m *VerifyRegisterTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRegisterTokenRsp.Unmarshal(m, b)
}
func (m *VerifyRegisterTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRegisterTokenRsp.Marshal(b, m, deterministic)
}
func (m *VerifyRegisterTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRegisterTokenRsp.Merge(m, src)
}
func (m *VerifyRegisterTokenRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyRegisterTokenRsp.Size(m)
}
func (m *VerifyRegisterTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRegisterTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRegisterTokenRsp proto.InternalMessageInfo

func (m *VerifyRegisterTokenRsp) GetTokenStatus() TokenStatus {
	if m != nil {
		return m.TokenStatus
	}
	return TokenStatus_OK
}

func (m *VerifyRegisterTokenRsp) GetClaims() *RegisterTokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type LoginTokenClaims struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginTokenClaims) Reset()         { *m = LoginTokenClaims{} }
func (m *LoginTokenClaims) String() string { return proto.CompactTextString(m) }
func (*LoginTokenClaims) ProtoMessage()    {}
func (*LoginTokenClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{5}
}

func (m *LoginTokenClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginTokenClaims.Unmarshal(m, b)
}
func (m *LoginTokenClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginTokenClaims.Marshal(b, m, deterministic)
}
func (m *LoginTokenClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginTokenClaims.Merge(m, src)
}
func (m *LoginTokenClaims) XXX_Size() int {
	return xxx_messageInfo_LoginTokenClaims.Size(m)
}
func (m *LoginTokenClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginTokenClaims.DiscardUnknown(m)
}

var xxx_messageInfo_LoginTokenClaims proto.InternalMessageInfo

func (m *LoginTokenClaims) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginTokenClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginTokenClaims) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *LoginTokenClaims) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *LoginTokenClaims) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type GetLoginTokenReq struct {
	Claims               *LoginTokenClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	SecretKey            string            `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetLoginTokenReq) Reset()         { *m = GetLoginTokenReq{} }
func (m *GetLoginTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetLoginTokenReq) ProtoMessage()    {}
func (*GetLoginTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{6}
}

func (m *GetLoginTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoginTokenReq.Unmarshal(m, b)
}
func (m *GetLoginTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoginTokenReq.Marshal(b, m, deterministic)
}
func (m *GetLoginTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoginTokenReq.Merge(m, src)
}
func (m *GetLoginTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetLoginTokenReq.Size(m)
}
func (m *GetLoginTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoginTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoginTokenReq proto.InternalMessageInfo

func (m *GetLoginTokenReq) GetClaims() *LoginTokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *GetLoginTokenReq) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type GetLoginTokenRsp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLoginTokenRsp) Reset()         { *m = GetLoginTokenRsp{} }
func (m *GetLoginTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetLoginTokenRsp) ProtoMessage()    {}
func (*GetLoginTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{7}
}

func (m *GetLoginTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLoginTokenRsp.Unmarshal(m, b)
}
func (m *GetLoginTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLoginTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetLoginTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLoginTokenRsp.Merge(m, src)
}
func (m *GetLoginTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetLoginTokenRsp.Size(m)
}
func (m *GetLoginTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLoginTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLoginTokenRsp proto.InternalMessageInfo

func (m *GetLoginTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyLoginTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SecretKey            string   `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyLoginTokenReq) Reset()         { *m = VerifyLoginTokenReq{} }
func (m *VerifyLoginTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyLoginTokenReq) ProtoMessage()    {}
func (*VerifyLoginTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{8}
}

func (m *VerifyLoginTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyLoginTokenReq.Unmarshal(m, b)
}
func (m *VerifyLoginTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyLoginTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyLoginTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyLoginTokenReq.Merge(m, src)
}
func (m *VerifyLoginTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyLoginTokenReq.Size(m)
}
func (m *VerifyLoginTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyLoginTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyLoginTokenReq proto.InternalMessageInfo

func (m *VerifyLoginTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifyLoginTokenReq) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type VerifyLoginTokenRsp struct {
	TokenStatus          TokenStatus       `protobuf:"varint,1,opt,name=token_status,json=tokenStatus,proto3,enum=proto.TokenStatus" json:"token_status,omitempty"`
	Claims               *LoginTokenClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VerifyLoginTokenRsp) Reset()         { *m = VerifyLoginTokenRsp{} }
func (m *VerifyLoginTokenRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyLoginTokenRsp) ProtoMessage()    {}
func (*VerifyLoginTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{9}
}

func (m *VerifyLoginTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyLoginTokenRsp.Unmarshal(m, b)
}
func (m *VerifyLoginTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyLoginTokenRsp.Marshal(b, m, deterministic)
}
func (m *VerifyLoginTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyLoginTokenRsp.Merge(m, src)
}
func (m *VerifyLoginTokenRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyLoginTokenRsp.Size(m)
}
func (m *VerifyLoginTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyLoginTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyLoginTokenRsp proto.InternalMessageInfo

func (m *VerifyLoginTokenRsp) GetTokenStatus() TokenStatus {
	if m != nil {
		return m.TokenStatus
	}
	return TokenStatus_OK
}

func (m *VerifyLoginTokenRsp) GetClaims() *LoginTokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type RefreshLoginTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AddSeconds           int64    `protobuf:"varint,2,opt,name=add_seconds,json=addSeconds,proto3" json:"add_seconds,omitempty"`
	SecretKey            string   `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshLoginTokenReq) Reset()         { *m = RefreshLoginTokenReq{} }
func (m *RefreshLoginTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshLoginTokenReq) ProtoMessage()    {}
func (*RefreshLoginTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{10}
}

func (m *RefreshLoginTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshLoginTokenReq.Unmarshal(m, b)
}
func (m *RefreshLoginTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshLoginTokenReq.Marshal(b, m, deterministic)
}
func (m *RefreshLoginTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshLoginTokenReq.Merge(m, src)
}
func (m *RefreshLoginTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshLoginTokenReq.Size(m)
}
func (m *RefreshLoginTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshLoginTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshLoginTokenReq proto.InternalMessageInfo

func (m *RefreshLoginTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshLoginTokenReq) GetAddSeconds() int64 {
	if m != nil {
		return m.AddSeconds
	}
	return 0
}

func (m *RefreshLoginTokenReq) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type RefreshLoginTokenRsp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshLoginTokenRsp) Reset()         { *m = RefreshLoginTokenRsp{} }
func (m *RefreshLoginTokenRsp) String() string { return proto.CompactTextString(m) }
func (*RefreshLoginTokenRsp) ProtoMessage()    {}
func (*RefreshLoginTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{11}
}

func (m *RefreshLoginTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshLoginTokenRsp.Unmarshal(m, b)
}
func (m *RefreshLoginTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshLoginTokenRsp.Marshal(b, m, deterministic)
}
func (m *RefreshLoginTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshLoginTokenRsp.Merge(m, src)
}
func (m *RefreshLoginTokenRsp) XXX_Size() int {
	return xxx_messageInfo_RefreshLoginTokenRsp.Size(m)
}
func (m *RefreshLoginTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshLoginTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshLoginTokenRsp proto.InternalMessageInfo

func (m *RefreshLoginTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CancelTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTokenReq) Reset()         { *m = CancelTokenReq{} }
func (m *CancelTokenReq) String() string { return proto.CompactTextString(m) }
func (*CancelTokenReq) ProtoMessage()    {}
func (*CancelTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{12}
}

func (m *CancelTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTokenReq.Unmarshal(m, b)
}
func (m *CancelTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTokenReq.Marshal(b, m, deterministic)
}
func (m *CancelTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTokenReq.Merge(m, src)
}
func (m *CancelTokenReq) XXX_Size() int {
	return xxx_messageInfo_CancelTokenReq.Size(m)
}
func (m *CancelTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTokenReq proto.InternalMessageInfo

func (m *CancelTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CancelTokenRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTokenRsp) Reset()         { *m = CancelTokenRsp{} }
func (m *CancelTokenRsp) String() string { return proto.CompactTextString(m) }
func (*CancelTokenRsp) ProtoMessage()    {}
func (*CancelTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{13}
}

func (m *CancelTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTokenRsp.Unmarshal(m, b)
}
func (m *CancelTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTokenRsp.Marshal(b, m, deterministic)
}
func (m *CancelTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTokenRsp.Merge(m, src)
}
func (m *CancelTokenRsp) XXX_Size() int {
	return xxx_messageInfo_CancelTokenRsp.Size(m)
}
func (m *CancelTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTokenRsp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.TokenStatus", TokenStatus_name, TokenStatus_value)
	proto.RegisterType((*RegisterTokenClaims)(nil), "proto.RegisterTokenClaims")
	proto.RegisterType((*GetRegisterTokenReq)(nil), "proto.GetRegisterTokenReq")
	proto.RegisterType((*GetRegisterTokenRsp)(nil), "proto.GetRegisterTokenRsp")
	proto.RegisterType((*VerifyRegisterTokenReq)(nil), "proto.VerifyRegisterTokenReq")
	proto.RegisterType((*VerifyRegisterTokenRsp)(nil), "proto.VerifyRegisterTokenRsp")
	proto.RegisterType((*LoginTokenClaims)(nil), "proto.LoginTokenClaims")
	proto.RegisterType((*GetLoginTokenReq)(nil), "proto.GetLoginTokenReq")
	proto.RegisterType((*GetLoginTokenRsp)(nil), "proto.GetLoginTokenRsp")
	proto.RegisterType((*VerifyLoginTokenReq)(nil), "proto.VerifyLoginTokenReq")
	proto.RegisterType((*VerifyLoginTokenRsp)(nil), "proto.VerifyLoginTokenRsp")
	proto.RegisterType((*RefreshLoginTokenReq)(nil), "proto.RefreshLoginTokenReq")
	proto.RegisterType((*RefreshLoginTokenRsp)(nil), "proto.RefreshLoginTokenRsp")
	proto.RegisterType((*CancelTokenReq)(nil), "proto.CancelTokenReq")
	proto.RegisterType((*CancelTokenRsp)(nil), "proto.CancelTokenRsp")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab) }

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0xc5, 0x71, 0x13, 0xc8, 0x98, 0x22, 0x77, 0x43, 0x49, 0xe4, 0x0a, 0x15, 0xf9, 0x50, 0x45,
	0x6d, 0x05, 0x52, 0xaa, 0x1e, 0x39, 0x44, 0x49, 0x84, 0x02, 0x29, 0x54, 0x4b, 0x8b, 0x7a, 0x8b,
	0x96, 0x78, 0x00, 0x2b, 0x89, 0xed, 0x7a, 0x97, 0xaa, 0x39, 0xf4, 0xd4, 0x5f, 0xe8, 0x7f, 0xf5,
	0x97, 0x90, 0xd7, 0x4e, 0x62, 0x3b, 0x6b, 0x88, 0x38, 0x59, 0xb3, 0x6f, 0xfc, 0xe6, 0xcd, 0xbc,
	0xd9, 0x05, 0x43, 0xf8, 0x63, 0xf4, 0x0e, 0x83, 0xd0, 0x17, 0x3e, 0x29, 0xcb, 0x8f, 0x7d, 0x0a,
	0x35, 0x8a, 0xb7, 0x2e, 0x17, 0x18, 0x7e, 0x8b, 0xd0, 0xce, 0x84, 0xb9, 0x53, 0x4e, 0x76, 0xa1,
	0x8c, 0x53, 0xe6, 0x4e, 0x1a, 0xda, 0x81, 0xd6, 0xac, 0xd2, 0x38, 0x20, 0xfb, 0x00, 0xf8, 0x3b,
	0x70, 0x43, 0xe4, 0x43, 0x26, 0x1a, 0xa5, 0x03, 0xad, 0xa9, 0xd3, 0x6a, 0x72, 0xd2, 0x16, 0xf6,
	0x1d, 0xd4, 0x4e, 0x50, 0x64, 0xe8, 0x28, 0xfe, 0x24, 0x2d, 0xa8, 0x8c, 0x24, 0xab, 0x24, 0x33,
	0x5a, 0x56, 0xac, 0xe0, 0x50, 0x51, 0x97, 0x26, 0x99, 0x51, 0x25, 0x8e, 0xa3, 0x10, 0xc5, 0x70,
	0x8c, 0x33, 0x59, 0xa9, 0x4a, 0xab, 0xf1, 0xc9, 0x19, 0xce, 0xec, 0x0f, 0x8a, 0x4a, 0x3c, 0x88,
	0x54, 0xcb, 0x16, 0xe7, 0xaa, 0x65, 0x60, 0x7f, 0x81, 0xbd, 0x2b, 0x0c, 0xdd, 0x9b, 0xd9, 0x8a,
	0x32, 0x65, 0xfe, 0x53, 0xb5, 0xff, 0x6a, 0x6a, 0x3e, 0x1e, 0x90, 0xcf, 0xb0, 0x2d, 0x29, 0x86,
	0x5c, 0x30, 0x71, 0x1f, 0xf7, 0xbb, 0xd3, 0x22, 0x49, 0xbf, 0x32, 0xed, 0x52, 0x22, 0x34, 0xb6,
	0x22, 0x0e, 0x52, 0x03, 0x2a, 0xad, 0x3b, 0x20, 0xfb, 0x9f, 0x06, 0xe6, 0xc0, 0xbf, 0x75, 0xbd,
	0xb4, 0x6b, 0x75, 0xd8, 0xbc, 0xe7, 0x18, 0x0e, 0x5d, 0x47, 0x96, 0xd6, 0x69, 0x25, 0x0a, 0xfb,
	0xce, 0xd2, 0xce, 0x52, 0xda, 0x4e, 0x0b, 0xb6, 0x3c, 0x77, 0x34, 0xf6, 0xd8, 0x14, 0x1b, 0xba,
	0x04, 0x16, 0x31, 0xd9, 0x83, 0x0a, 0xfb, 0xc5, 0x04, 0x0b, 0x1b, 0x2f, 0x24, 0x92, 0x44, 0xb9,
	0x15, 0x28, 0xe7, 0x57, 0xe0, 0x1a, 0xcc, 0x13, 0x14, 0x4b, 0x61, 0xd1, 0x94, 0x8f, 0x72, 0xfe,
	0xd7, 0x93, 0xf6, 0xf2, 0xf2, 0xd7, 0x35, 0xbf, 0x99, 0xaf, 0x51, 0xe8, 0xfc, 0x29, 0xd4, 0x62,
	0xa7, 0xb2, 0x82, 0x9e, 0x65, 0xfb, 0x1f, 0x05, 0xd7, 0xf3, 0x2d, 0x3f, 0xca, 0x59, 0xfe, 0xd4,
	0x4c, 0xec, 0x09, 0xec, 0x52, 0xbc, 0x09, 0x91, 0xdf, 0xad, 0xd3, 0xcb, 0x5b, 0x30, 0x98, 0xe3,
	0x0c, 0x39, 0x8e, 0x7c, 0xcf, 0xe1, 0xc9, 0x4d, 0x05, 0xe6, 0x38, 0x97, 0xf1, 0x49, 0xae, 0x59,
	0x3d, 0xdf, 0xec, 0x47, 0x55, 0xb5, 0xc2, 0x31, 0xbf, 0x83, 0x9d, 0x0e, 0xf3, 0x46, 0x38, 0x79,
	0x5c, 0x95, 0x6d, 0x66, 0xf3, 0x78, 0xf0, 0xfe, 0x18, 0x8c, 0xd4, 0x88, 0x48, 0x05, 0x4a, 0x17,
	0x67, 0xe6, 0x06, 0x31, 0x60, 0xb3, 0x7f, 0x7e, 0xd5, 0x1e, 0xf4, 0xbb, 0xa6, 0x16, 0x05, 0xbd,
	0x1f, 0x5f, 0xfb, 0xb4, 0xd7, 0x35, 0x4b, 0x64, 0x1b, 0xb6, 0x3a, 0xed, 0xf3, 0x4e, 0x6f, 0xd0,
	0xeb, 0x9a, 0x7a, 0xeb, 0xbf, 0x0e, 0x65, 0xf9, 0x3f, 0x19, 0xc8, 0x9d, 0xc8, 0x5c, 0x18, 0x32,
	0xbf, 0x46, 0x8a, 0x37, 0xc9, 0x2a, 0xc4, 0x78, 0x60, 0x6f, 0x90, 0xef, 0x73, 0xaf, 0xb3, 0x84,
	0xfb, 0xc9, 0x4f, 0xea, 0xd7, 0xc4, 0x7a, 0x0c, 0x96, 0xb4, 0x1d, 0x78, 0x99, 0x59, 0x5c, 0x52,
	0x5f, 0xaa, 0xc8, 0xb8, 0x6a, 0xa9, 0x01, 0x49, 0x32, 0x00, 0x33, 0xbf, 0x87, 0x8b, 0x4e, 0x15,
	0xcb, 0x6e, 0x15, 0x62, 0x92, 0xed, 0x02, 0x5e, 0xad, 0x18, 0x4d, 0xde, 0x2c, 0xde, 0x9f, 0xd5,
	0x85, 0xb3, 0x8a, 0x41, 0x49, 0x78, 0x0c, 0x46, 0xca, 0x63, 0xf2, 0x3a, 0xc9, 0xce, 0xee, 0x87,
	0xa5, 0x3a, 0x8e, 0x7e, 0xbf, 0xae, 0xc8, 0xf3, 0x4f, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a,
	0xe6, 0x1b, 0x9e, 0xab, 0x06, 0x00, 0x00,
}
