// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_Empty          Status = 0
	Status_OK             Status = 200
	Status_TokenRefreshed Status = 201
	Status_ParamInvalid   Status = 300
	Status_TokenInvalid   Status = 400
	Status_TokenExpired   Status = 401
	Status_TokenCanceled  Status = 402
)

var Status_name = map[int32]string{
	0:   "Empty",
	200: "OK",
	201: "TokenRefreshed",
	300: "ParamInvalid",
	400: "TokenInvalid",
	401: "TokenExpired",
	402: "TokenCanceled",
}

var Status_value = map[string]int32{
	"Empty":          0,
	"OK":             200,
	"TokenRefreshed": 201,
	"ParamInvalid":   300,
	"TokenInvalid":   400,
	"TokenExpired":   401,
	"TokenCanceled":  402,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

type InviteClaims struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteClaims) Reset()         { *m = InviteClaims{} }
func (m *InviteClaims) String() string { return proto.CompactTextString(m) }
func (*InviteClaims) ProtoMessage()    {}
func (*InviteClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *InviteClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteClaims.Unmarshal(m, b)
}
func (m *InviteClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteClaims.Marshal(b, m, deterministic)
}
func (m *InviteClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteClaims.Merge(m, src)
}
func (m *InviteClaims) XXX_Size() int {
	return xxx_messageInfo_InviteClaims.Size(m)
}
func (m *InviteClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteClaims.DiscardUnknown(m)
}

var xxx_messageInfo_InviteClaims proto.InternalMessageInfo

func (m *InviteClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetInviteTokenReq struct {
	Claims               *InviteClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetInviteTokenReq) Reset()         { *m = GetInviteTokenReq{} }
func (m *GetInviteTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetInviteTokenReq) ProtoMessage()    {}
func (*GetInviteTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{1}
}

func (m *GetInviteTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInviteTokenReq.Unmarshal(m, b)
}
func (m *GetInviteTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInviteTokenReq.Marshal(b, m, deterministic)
}
func (m *GetInviteTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInviteTokenReq.Merge(m, src)
}
func (m *GetInviteTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetInviteTokenReq.Size(m)
}
func (m *GetInviteTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInviteTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInviteTokenReq proto.InternalMessageInfo

func (m *GetInviteTokenReq) GetClaims() *InviteClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type GetInviteTokenRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInviteTokenRsp) Reset()         { *m = GetInviteTokenRsp{} }
func (m *GetInviteTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetInviteTokenRsp) ProtoMessage()    {}
func (*GetInviteTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{2}
}

func (m *GetInviteTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInviteTokenRsp.Unmarshal(m, b)
}
func (m *GetInviteTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInviteTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetInviteTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInviteTokenRsp.Merge(m, src)
}
func (m *GetInviteTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetInviteTokenRsp.Size(m)
}
func (m *GetInviteTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInviteTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInviteTokenRsp proto.InternalMessageInfo

func (m *GetInviteTokenRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *GetInviteTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyInviteTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyInviteTokenReq) Reset()         { *m = VerifyInviteTokenReq{} }
func (m *VerifyInviteTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyInviteTokenReq) ProtoMessage()    {}
func (*VerifyInviteTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{3}
}

func (m *VerifyInviteTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyInviteTokenReq.Unmarshal(m, b)
}
func (m *VerifyInviteTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyInviteTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyInviteTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyInviteTokenReq.Merge(m, src)
}
func (m *VerifyInviteTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyInviteTokenReq.Size(m)
}
func (m *VerifyInviteTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyInviteTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyInviteTokenReq proto.InternalMessageInfo

func (m *VerifyInviteTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyInviteTokenRsp struct {
	Status               Status        `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Claims               *InviteClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VerifyInviteTokenRsp) Reset()         { *m = VerifyInviteTokenRsp{} }
func (m *VerifyInviteTokenRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyInviteTokenRsp) ProtoMessage()    {}
func (*VerifyInviteTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{4}
}

func (m *VerifyInviteTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyInviteTokenRsp.Unmarshal(m, b)
}
func (m *VerifyInviteTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyInviteTokenRsp.Marshal(b, m, deterministic)
}
func (m *VerifyInviteTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyInviteTokenRsp.Merge(m, src)
}
func (m *VerifyInviteTokenRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyInviteTokenRsp.Size(m)
}
func (m *VerifyInviteTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyInviteTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyInviteTokenRsp proto.InternalMessageInfo

func (m *VerifyInviteTokenRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *VerifyInviteTokenRsp) GetClaims() *InviteClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type AuthClaims struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthClaims) Reset()         { *m = AuthClaims{} }
func (m *AuthClaims) String() string { return proto.CompactTextString(m) }
func (*AuthClaims) ProtoMessage()    {}
func (*AuthClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{5}
}

func (m *AuthClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthClaims.Unmarshal(m, b)
}
func (m *AuthClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthClaims.Marshal(b, m, deterministic)
}
func (m *AuthClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthClaims.Merge(m, src)
}
func (m *AuthClaims) XXX_Size() int {
	return xxx_messageInfo_AuthClaims.Size(m)
}
func (m *AuthClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthClaims.DiscardUnknown(m)
}

var xxx_messageInfo_AuthClaims proto.InternalMessageInfo

func (m *AuthClaims) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthClaims) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AuthClaims) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AuthClaims) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type GetAuthTokenReq struct {
	Claims               *AuthClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAuthTokenReq) Reset()         { *m = GetAuthTokenReq{} }
func (m *GetAuthTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAuthTokenReq) ProtoMessage()    {}
func (*GetAuthTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{6}
}

func (m *GetAuthTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthTokenReq.Unmarshal(m, b)
}
func (m *GetAuthTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthTokenReq.Marshal(b, m, deterministic)
}
func (m *GetAuthTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthTokenReq.Merge(m, src)
}
func (m *GetAuthTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAuthTokenReq.Size(m)
}
func (m *GetAuthTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthTokenReq proto.InternalMessageInfo

func (m *GetAuthTokenReq) GetClaims() *AuthClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type GetAuthTokenRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthTokenRsp) Reset()         { *m = GetAuthTokenRsp{} }
func (m *GetAuthTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetAuthTokenRsp) ProtoMessage()    {}
func (*GetAuthTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{7}
}

func (m *GetAuthTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthTokenRsp.Unmarshal(m, b)
}
func (m *GetAuthTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetAuthTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthTokenRsp.Merge(m, src)
}
func (m *GetAuthTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetAuthTokenRsp.Size(m)
}
func (m *GetAuthTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthTokenRsp proto.InternalMessageInfo

func (m *GetAuthTokenRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *GetAuthTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyAuthTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAuthTokenReq) Reset()         { *m = VerifyAuthTokenReq{} }
func (m *VerifyAuthTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyAuthTokenReq) ProtoMessage()    {}
func (*VerifyAuthTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{8}
}

func (m *VerifyAuthTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAuthTokenReq.Unmarshal(m, b)
}
func (m *VerifyAuthTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAuthTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyAuthTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAuthTokenReq.Merge(m, src)
}
func (m *VerifyAuthTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyAuthTokenReq.Size(m)
}
func (m *VerifyAuthTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAuthTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAuthTokenReq proto.InternalMessageInfo

func (m *VerifyAuthTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyAuthTokenRsp struct {
	Status               Status      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Claims               *AuthClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	FreshToken           string      `protobuf:"bytes,3,opt,name=fresh_token,json=freshToken,proto3" json:"fresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifyAuthTokenRsp) Reset()         { *m = VerifyAuthTokenRsp{} }
func (m *VerifyAuthTokenRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyAuthTokenRsp) ProtoMessage()    {}
func (*VerifyAuthTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{9}
}

func (m *VerifyAuthTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAuthTokenRsp.Unmarshal(m, b)
}
func (m *VerifyAuthTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAuthTokenRsp.Marshal(b, m, deterministic)
}
func (m *VerifyAuthTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAuthTokenRsp.Merge(m, src)
}
func (m *VerifyAuthTokenRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyAuthTokenRsp.Size(m)
}
func (m *VerifyAuthTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAuthTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAuthTokenRsp proto.InternalMessageInfo

func (m *VerifyAuthTokenRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func (m *VerifyAuthTokenRsp) GetClaims() *AuthClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *VerifyAuthTokenRsp) GetFreshToken() string {
	if m != nil {
		return m.FreshToken
	}
	return ""
}

type CancelTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTokenReq) Reset()         { *m = CancelTokenReq{} }
func (m *CancelTokenReq) String() string { return proto.CompactTextString(m) }
func (*CancelTokenReq) ProtoMessage()    {}
func (*CancelTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{10}
}

func (m *CancelTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTokenReq.Unmarshal(m, b)
}
func (m *CancelTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTokenReq.Marshal(b, m, deterministic)
}
func (m *CancelTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTokenReq.Merge(m, src)
}
func (m *CancelTokenReq) XXX_Size() int {
	return xxx_messageInfo_CancelTokenReq.Size(m)
}
func (m *CancelTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTokenReq proto.InternalMessageInfo

func (m *CancelTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CancelTokenRsp struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelTokenRsp) Reset()         { *m = CancelTokenRsp{} }
func (m *CancelTokenRsp) String() string { return proto.CompactTextString(m) }
func (*CancelTokenRsp) ProtoMessage()    {}
func (*CancelTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{11}
}

func (m *CancelTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelTokenRsp.Unmarshal(m, b)
}
func (m *CancelTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelTokenRsp.Marshal(b, m, deterministic)
}
func (m *CancelTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelTokenRsp.Merge(m, src)
}
func (m *CancelTokenRsp) XXX_Size() int {
	return xxx_messageInfo_CancelTokenRsp.Size(m)
}
func (m *CancelTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CancelTokenRsp proto.InternalMessageInfo

func (m *CancelTokenRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Empty
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*InviteClaims)(nil), "proto.InviteClaims")
	proto.RegisterType((*GetInviteTokenReq)(nil), "proto.GetInviteTokenReq")
	proto.RegisterType((*GetInviteTokenRsp)(nil), "proto.GetInviteTokenRsp")
	proto.RegisterType((*VerifyInviteTokenReq)(nil), "proto.VerifyInviteTokenReq")
	proto.RegisterType((*VerifyInviteTokenRsp)(nil), "proto.VerifyInviteTokenRsp")
	proto.RegisterType((*AuthClaims)(nil), "proto.AuthClaims")
	proto.RegisterType((*GetAuthTokenReq)(nil), "proto.GetAuthTokenReq")
	proto.RegisterType((*GetAuthTokenRsp)(nil), "proto.GetAuthTokenRsp")
	proto.RegisterType((*VerifyAuthTokenReq)(nil), "proto.VerifyAuthTokenReq")
	proto.RegisterType((*VerifyAuthTokenRsp)(nil), "proto.VerifyAuthTokenRsp")
	proto.RegisterType((*CancelTokenReq)(nil), "proto.CancelTokenReq")
	proto.RegisterType((*CancelTokenRsp)(nil), "proto.CancelTokenRsp")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab) }

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x6d, 0xec, 0x92, 0x49, 0x9a, 0x3a, 0xd3, 0x52, 0x8c, 0x7b, 0x00, 0x59, 0x80, 0x68,
	0x41, 0x3d, 0x84, 0x03, 0x17, 0x90, 0x8a, 0xaa, 0x52, 0x45, 0x48, 0xb4, 0x32, 0x3f, 0xd7, 0xc8,
	0x8d, 0xb7, 0x74, 0xa9, 0xed, 0x18, 0xdb, 0xa9, 0xe8, 0x85, 0x2b, 0x17, 0x0e, 0xc0, 0x73, 0xf0,
	0x20, 0xf0, 0x2e, 0x3c, 0x04, 0xf2, 0xec, 0xe2, 0xd8, 0x8e, 0xa3, 0x44, 0xe2, 0x64, 0xcd, 0x37,
	0xdf, 0x7e, 0xf3, 0xcd, 0xcc, 0xae, 0xa1, 0x9d, 0x8d, 0x2f, 0x58, 0xb4, 0x17, 0x27, 0xe3, 0x6c,
	0x8c, 0x3a, 0x7d, 0x9c, 0xbb, 0xd0, 0x19, 0x44, 0x97, 0x3c, 0x63, 0x07, 0x81, 0xc7, 0xc3, 0x14,
	0x37, 0x41, 0x67, 0xa1, 0xc7, 0x03, 0x4b, 0xb9, 0xa3, 0x3c, 0x68, 0xb9, 0x22, 0x70, 0xf6, 0xa1,
	0x77, 0xc4, 0x32, 0x41, 0x7c, 0x93, 0x8b, 0xb8, 0xec, 0x23, 0x3e, 0x04, 0x63, 0x44, 0x87, 0x88,
	0xdb, 0xee, 0x6f, 0x08, 0xe5, 0xbd, 0xb2, 0x9e, 0x2b, 0x29, 0xce, 0xc9, 0x8c, 0x42, 0x1a, 0xe3,
	0x3d, 0x30, 0xd2, 0xcc, 0xcb, 0x26, 0x42, 0xa1, 0xdb, 0x5f, 0x93, 0x0a, 0xaf, 0x09, 0x74, 0x65,
	0x32, 0xf7, 0x44, 0xce, 0x2d, 0x55, 0x78, 0xa2, 0xc0, 0x79, 0x04, 0x9b, 0xef, 0x58, 0xc2, 0xcf,
	0xae, 0x6a, 0xb6, 0x0a, 0xb6, 0x52, 0x66, 0x7f, 0x68, 0x62, 0x2f, 0x6f, 0x61, 0xda, 0xab, 0xba,
	0xb8, 0xd7, 0xaf, 0x0a, 0xc0, 0xf3, 0x49, 0x76, 0x2e, 0x47, 0x7a, 0x13, 0x56, 0x27, 0x29, 0x4b,
	0x86, 0xdc, 0xa7, 0x1a, 0x9a, 0x6b, 0xe4, 0xe1, 0xc0, 0x9f, 0xce, 0x5a, 0x2d, 0xcd, 0x1a, 0xb7,
	0xc0, 0x08, 0xc7, 0xa7, 0x3c, 0x60, 0x96, 0x46, 0xb0, 0x8c, 0xd0, 0x86, 0xeb, 0x11, 0x1f, 0x5d,
	0x44, 0x5e, 0xc8, 0xac, 0x6b, 0x94, 0x29, 0x62, 0xdc, 0x86, 0x16, 0x0f, 0xbd, 0xf7, 0x6c, 0x38,
	0x49, 0x02, 0x4b, 0x17, 0x49, 0x02, 0xde, 0x26, 0x81, 0xf3, 0x14, 0xd6, 0x8f, 0x58, 0x96, 0x1b,
	0x2a, 0x66, 0xb4, 0x53, 0x5b, 0x5d, 0x4f, 0xb6, 0x33, 0x75, 0x5d, 0x34, 0xf3, 0xaa, 0x76, 0xfa,
	0x7f, 0xd7, 0xb6, 0x0b, 0x28, 0x16, 0x51, 0x31, 0xd4, 0xbc, 0xb4, 0x2f, 0xca, 0x2c, 0x79, 0xf9,
	0xfa, 0x3b, 0xb5, 0x9d, 0xcd, 0x6f, 0x12, 0x6f, 0x43, 0xfb, 0x2c, 0x61, 0xe9, 0xf9, 0x50, 0x98,
	0x10, 0x83, 0x07, 0x82, 0xa8, 0xaa, 0x73, 0x1f, 0xba, 0x07, 0x5e, 0x34, 0x62, 0xc1, 0x02, 0xc7,
	0x4f, 0xaa, 0xbc, 0xa5, 0xcd, 0xee, 0x7e, 0x06, 0x43, 0x20, 0xd8, 0x02, 0xfd, 0x30, 0x8c, 0xb3,
	0x2b, 0x73, 0x05, 0x57, 0x41, 0x3d, 0x7e, 0x69, 0xfe, 0x52, 0x70, 0x03, 0xba, 0xb2, 0x30, 0x79,
	0x62, 0xbe, 0xf9, 0x5b, 0xc1, 0x1e, 0x74, 0x4e, 0xbc, 0xc4, 0x0b, 0x07, 0xd1, 0xa5, 0x17, 0x70,
	0xdf, 0xfc, 0xa9, 0xe6, 0x10, 0xf1, 0xfe, 0x41, 0xdf, 0xb4, 0x02, 0x3a, 0xfc, 0x14, 0xf3, 0x84,
	0xf9, 0xe6, 0x77, 0x0d, 0x11, 0xd6, 0x08, 0x12, 0x4e, 0x99, 0x6f, 0xfe, 0xd0, 0xfa, 0x7f, 0x54,
	0xd0, 0x09, 0xc4, 0x17, 0xd0, 0xad, 0xbe, 0x54, 0xb4, 0xa4, 0xe5, 0x99, 0x5f, 0x80, 0x3d, 0x27,
	0x93, 0xc6, 0xce, 0x0a, 0x1e, 0x43, 0x6f, 0xe6, 0xc5, 0xe1, 0xb6, 0x3c, 0xd0, 0xf4, 0x72, 0xed,
	0xf9, 0x49, 0x12, 0xdc, 0x87, 0x4e, 0xf9, 0x26, 0xe2, 0xd6, 0xb4, 0x78, 0xf9, 0x2e, 0xd9, 0x8d,
	0x38, 0x29, 0x0c, 0x60, 0xbd, 0x76, 0x9d, 0xf0, 0x56, 0xa5, 0x66, 0x45, 0x67, 0x5e, 0x8a, 0xa4,
	0x9e, 0x41, 0xbb, 0xb4, 0x68, 0xbc, 0x21, 0xb9, 0xd5, 0x4b, 0x62, 0x37, 0xc1, 0xf9, 0xf1, 0x53,
	0x83, 0xf0, 0xc7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xce, 0xcc, 0x8f, 0x87, 0x93, 0x05, 0x00,
	0x00,
}
