// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK              Status = 0
	Status_ErrTokenInvalid Status = 1
	Status_ErrTokenExpired Status = 2
)

var Status_name = map[int32]string{
	0: "OK",
	1: "ErrTokenInvalid",
	2: "ErrTokenExpired",
}

var Status_value = map[string]int32{
	"OK":              0,
	"ErrTokenInvalid": 1,
	"ErrTokenExpired": 2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

type InviteClaims struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteClaims) Reset()         { *m = InviteClaims{} }
func (m *InviteClaims) String() string { return proto.CompactTextString(m) }
func (*InviteClaims) ProtoMessage()    {}
func (*InviteClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{0}
}

func (m *InviteClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteClaims.Unmarshal(m, b)
}
func (m *InviteClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteClaims.Marshal(b, m, deterministic)
}
func (m *InviteClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteClaims.Merge(m, src)
}
func (m *InviteClaims) XXX_Size() int {
	return xxx_messageInfo_InviteClaims.Size(m)
}
func (m *InviteClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteClaims.DiscardUnknown(m)
}

var xxx_messageInfo_InviteClaims proto.InternalMessageInfo

func (m *InviteClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetInviteTokenReq struct {
	Claims               *InviteClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetInviteTokenReq) Reset()         { *m = GetInviteTokenReq{} }
func (m *GetInviteTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetInviteTokenReq) ProtoMessage()    {}
func (*GetInviteTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{1}
}

func (m *GetInviteTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInviteTokenReq.Unmarshal(m, b)
}
func (m *GetInviteTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInviteTokenReq.Marshal(b, m, deterministic)
}
func (m *GetInviteTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInviteTokenReq.Merge(m, src)
}
func (m *GetInviteTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetInviteTokenReq.Size(m)
}
func (m *GetInviteTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInviteTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInviteTokenReq proto.InternalMessageInfo

func (m *GetInviteTokenReq) GetClaims() *InviteClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type GetInviteTokenRsp struct {
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInviteTokenRsp) Reset()         { *m = GetInviteTokenRsp{} }
func (m *GetInviteTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetInviteTokenRsp) ProtoMessage()    {}
func (*GetInviteTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{2}
}

func (m *GetInviteTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInviteTokenRsp.Unmarshal(m, b)
}
func (m *GetInviteTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInviteTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetInviteTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInviteTokenRsp.Merge(m, src)
}
func (m *GetInviteTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetInviteTokenRsp.Size(m)
}
func (m *GetInviteTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInviteTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInviteTokenRsp proto.InternalMessageInfo

func (m *GetInviteTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyInviteReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyInviteReq) Reset()         { *m = VerifyInviteReq{} }
func (m *VerifyInviteReq) String() string { return proto.CompactTextString(m) }
func (*VerifyInviteReq) ProtoMessage()    {}
func (*VerifyInviteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{3}
}

func (m *VerifyInviteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyInviteReq.Unmarshal(m, b)
}
func (m *VerifyInviteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyInviteReq.Marshal(b, m, deterministic)
}
func (m *VerifyInviteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyInviteReq.Merge(m, src)
}
func (m *VerifyInviteReq) XXX_Size() int {
	return xxx_messageInfo_VerifyInviteReq.Size(m)
}
func (m *VerifyInviteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyInviteReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyInviteReq proto.InternalMessageInfo

func (m *VerifyInviteReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyInviteRsp struct {
	Status               Status        `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Claims               *InviteClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VerifyInviteRsp) Reset()         { *m = VerifyInviteRsp{} }
func (m *VerifyInviteRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyInviteRsp) ProtoMessage()    {}
func (*VerifyInviteRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{4}
}

func (m *VerifyInviteRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyInviteRsp.Unmarshal(m, b)
}
func (m *VerifyInviteRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyInviteRsp.Marshal(b, m, deterministic)
}
func (m *VerifyInviteRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyInviteRsp.Merge(m, src)
}
func (m *VerifyInviteRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyInviteRsp.Size(m)
}
func (m *VerifyInviteRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyInviteRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyInviteRsp proto.InternalMessageInfo

func (m *VerifyInviteRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *VerifyInviteRsp) GetClaims() *InviteClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type AuthClaims struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nickname             string   `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ImageUrl             string   `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthClaims) Reset()         { *m = AuthClaims{} }
func (m *AuthClaims) String() string { return proto.CompactTextString(m) }
func (*AuthClaims) ProtoMessage()    {}
func (*AuthClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{5}
}

func (m *AuthClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthClaims.Unmarshal(m, b)
}
func (m *AuthClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthClaims.Marshal(b, m, deterministic)
}
func (m *AuthClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthClaims.Merge(m, src)
}
func (m *AuthClaims) XXX_Size() int {
	return xxx_messageInfo_AuthClaims.Size(m)
}
func (m *AuthClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthClaims.DiscardUnknown(m)
}

var xxx_messageInfo_AuthClaims proto.InternalMessageInfo

func (m *AuthClaims) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthClaims) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthClaims) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AuthClaims) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AuthClaims) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type GetAuthTokenReq struct {
	Claims               *AuthClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetAuthTokenReq) Reset()         { *m = GetAuthTokenReq{} }
func (m *GetAuthTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAuthTokenReq) ProtoMessage()    {}
func (*GetAuthTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{6}
}

func (m *GetAuthTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthTokenReq.Unmarshal(m, b)
}
func (m *GetAuthTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthTokenReq.Marshal(b, m, deterministic)
}
func (m *GetAuthTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthTokenReq.Merge(m, src)
}
func (m *GetAuthTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAuthTokenReq.Size(m)
}
func (m *GetAuthTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthTokenReq proto.InternalMessageInfo

func (m *GetAuthTokenReq) GetClaims() *AuthClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

type GetAuthTokenRsp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthTokenRsp) Reset()         { *m = GetAuthTokenRsp{} }
func (m *GetAuthTokenRsp) String() string { return proto.CompactTextString(m) }
func (*GetAuthTokenRsp) ProtoMessage()    {}
func (*GetAuthTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{7}
}

func (m *GetAuthTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthTokenRsp.Unmarshal(m, b)
}
func (m *GetAuthTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthTokenRsp.Marshal(b, m, deterministic)
}
func (m *GetAuthTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthTokenRsp.Merge(m, src)
}
func (m *GetAuthTokenRsp) XXX_Size() int {
	return xxx_messageInfo_GetAuthTokenRsp.Size(m)
}
func (m *GetAuthTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthTokenRsp proto.InternalMessageInfo

func (m *GetAuthTokenRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyAuthReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyAuthReq) Reset()         { *m = VerifyAuthReq{} }
func (m *VerifyAuthReq) String() string { return proto.CompactTextString(m) }
func (*VerifyAuthReq) ProtoMessage()    {}
func (*VerifyAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{8}
}

func (m *VerifyAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAuthReq.Unmarshal(m, b)
}
func (m *VerifyAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAuthReq.Marshal(b, m, deterministic)
}
func (m *VerifyAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAuthReq.Merge(m, src)
}
func (m *VerifyAuthReq) XXX_Size() int {
	return xxx_messageInfo_VerifyAuthReq.Size(m)
}
func (m *VerifyAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAuthReq proto.InternalMessageInfo

func (m *VerifyAuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyAuthRsp struct {
	Status               Status      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	Claims               *AuthClaims `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifyAuthRsp) Reset()         { *m = VerifyAuthRsp{} }
func (m *VerifyAuthRsp) String() string { return proto.CompactTextString(m) }
func (*VerifyAuthRsp) ProtoMessage()    {}
func (*VerifyAuthRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aff0bcd502840ab, []int{9}
}

func (m *VerifyAuthRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAuthRsp.Unmarshal(m, b)
}
func (m *VerifyAuthRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAuthRsp.Marshal(b, m, deterministic)
}
func (m *VerifyAuthRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAuthRsp.Merge(m, src)
}
func (m *VerifyAuthRsp) XXX_Size() int {
	return xxx_messageInfo_VerifyAuthRsp.Size(m)
}
func (m *VerifyAuthRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAuthRsp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAuthRsp proto.InternalMessageInfo

func (m *VerifyAuthRsp) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *VerifyAuthRsp) GetClaims() *AuthClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*InviteClaims)(nil), "proto.InviteClaims")
	proto.RegisterType((*GetInviteTokenReq)(nil), "proto.GetInviteTokenReq")
	proto.RegisterType((*GetInviteTokenRsp)(nil), "proto.GetInviteTokenRsp")
	proto.RegisterType((*VerifyInviteReq)(nil), "proto.VerifyInviteReq")
	proto.RegisterType((*VerifyInviteRsp)(nil), "proto.VerifyInviteRsp")
	proto.RegisterType((*AuthClaims)(nil), "proto.AuthClaims")
	proto.RegisterType((*GetAuthTokenReq)(nil), "proto.GetAuthTokenReq")
	proto.RegisterType((*GetAuthTokenRsp)(nil), "proto.GetAuthTokenRsp")
	proto.RegisterType((*VerifyAuthReq)(nil), "proto.VerifyAuthReq")
	proto.RegisterType((*VerifyAuthRsp)(nil), "proto.VerifyAuthRsp")
}

func init() { proto.RegisterFile("token.proto", fileDescriptor_3aff0bcd502840ab) }

var fileDescriptor_3aff0bcd502840ab = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x25, 0xa1, 0x49, 0xcb, 0xf0, 0x6d, 0x10, 0x8d, 0xd2, 0x4b, 0x15, 0x15, 0x51, 0x5a, 0x89,
	0x03, 0xbd, 0xa1, 0x1e, 0xa8, 0x2a, 0x8a, 0x50, 0x0f, 0x95, 0xd2, 0x8f, 0x2b, 0x0a, 0xc4, 0x6d,
	0x2d, 0xf2, 0x55, 0xc7, 0x41, 0xdd, 0xff, 0xb0, 0xd2, 0xfe, 0xe5, 0x55, 0x6c, 0x6f, 0x70, 0x02,
	0x68, 0xf7, 0x64, 0xcd, 0x9b, 0x37, 0x33, 0xcf, 0xf3, 0x06, 0x9a, 0x2c, 0x3e, 0xe0, 0x68, 0x96,
	0xd0, 0x98, 0xc5, 0xc8, 0xe0, 0x8f, 0xf3, 0x06, 0x5a, 0x9b, 0xe8, 0x48, 0x18, 0xfe, 0x1c, 0x78,
	0x24, 0x4c, 0xd1, 0x10, 0x0c, 0x1c, 0x7a, 0x24, 0xb0, 0xb4, 0xd7, 0xda, 0xdb, 0x86, 0x2b, 0x02,
	0x67, 0x09, 0xfd, 0x35, 0x66, 0x82, 0xf8, 0x23, 0x6f, 0xe2, 0xe2, 0x7f, 0xe8, 0x3d, 0x98, 0x7b,
	0x5e, 0xc4, 0xb9, 0xcd, 0xf9, 0x40, 0x74, 0x9e, 0xa9, 0xfd, 0x5c, 0x49, 0x71, 0xa6, 0x67, 0x1d,
	0xd2, 0x24, 0x1f, 0xc6, 0x25, 0x59, 0xba, 0x18, 0xc6, 0x03, 0x67, 0x02, 0xdd, 0x5f, 0x98, 0x92,
	0xdf, 0x37, 0x82, 0x9d, 0x8f, 0x2a, 0x88, 0x9a, 0x4a, 0xc4, 0x15, 0x62, 0x9a, 0xa0, 0x31, 0x98,
	0x29, 0xf3, 0x58, 0x26, 0x34, 0x75, 0xe6, 0x6d, 0xa9, 0xe9, 0x3b, 0x07, 0x5d, 0x99, 0x54, 0xa4,
	0xeb, 0x8f, 0x4b, 0xbf, 0xd5, 0x00, 0x3e, 0x65, 0xec, 0xaf, 0xdc, 0xd0, 0x4b, 0x78, 0x9e, 0xa5,
	0x98, 0x6e, 0x89, 0xcf, 0x67, 0xd4, 0x5d, 0x33, 0x0f, 0x37, 0xfe, 0x69, 0x75, 0xba, 0xb2, 0x3a,
	0x34, 0x02, 0x33, 0x8c, 0x77, 0x24, 0xc0, 0x56, 0x9d, 0xc3, 0x32, 0x42, 0x36, 0xbc, 0x88, 0xc8,
	0xfe, 0x10, 0x79, 0x21, 0xb6, 0x9e, 0xf1, 0x4c, 0x11, 0xa3, 0x57, 0xd0, 0x20, 0xa1, 0xf7, 0x07,
	0x6f, 0x33, 0x1a, 0x58, 0x86, 0x48, 0x72, 0xe0, 0x27, 0x0d, 0x9c, 0x8f, 0xd0, 0x5d, 0x63, 0x96,
	0x0b, 0x2a, 0x9c, 0x98, 0x56, 0x9c, 0xe8, 0xcb, 0xef, 0x9c, 0x54, 0x17, 0x9f, 0x99, 0x54, 0xaa,
	0x55, 0x17, 0x4a, 0xcb, 0x1d, 0x43, 0x5b, 0x2c, 0x37, 0xe7, 0x5e, 0xf7, 0xc0, 0x2b, 0xd1, 0x9e,
	0xee, 0xc0, 0xb4, 0xe2, 0xc0, 0x75, 0xc9, 0xef, 0x16, 0x60, 0x8a, 0x62, 0x64, 0x82, 0xfe, 0xed,
	0x6b, 0xaf, 0x86, 0x06, 0xd0, 0x5d, 0x51, 0xca, 0x3f, 0xb0, 0x89, 0x8e, 0x5e, 0x40, 0xfc, 0x9e,
	0xa6, 0x82, 0xab, 0xff, 0x09, 0xa1, 0xd8, 0xef, 0xe9, 0xf3, 0x3b, 0x1d, 0x0c, 0x0e, 0xa1, 0x2f,
	0xd0, 0x29, 0x1f, 0x20, 0xb2, 0xe4, 0xc8, 0xb3, 0xcb, 0xb6, 0xaf, 0x64, 0xd2, 0xc4, 0xa9, 0xa1,
	0x25, 0xb4, 0xd4, 0xa3, 0x43, 0x23, 0xc9, 0xad, 0x9c, 0xac, 0x7d, 0x11, 0x7f, 0xe8, 0xa0, 0x5a,
	0x50, 0x74, 0xa8, 0xb8, 0x6a, 0x5f, 0xc4, 0x79, 0x87, 0x05, 0xc0, 0x69, 0xe9, 0x68, 0x58, 0x9a,
	0x24, 0xed, 0xb2, 0x2f, 0xa0, 0x79, 0xed, 0xce, 0xe4, 0xf0, 0x87, 0xfb, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0x58, 0x9a, 0x35, 0x0d, 0x04, 0x00, 0x00,
}
